# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpzs_order.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gpzs_order.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10gpzs_order.proto\"S\n\ngpzs_order\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03vol\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\x12\r\n\x05\x62sflg\x18\x04 \x01(\x05\x12\x0c\n\x04zsno\x18\x05 \x01(\x05\x62\x06proto3'
)




_GPZS_ORDER = _descriptor.Descriptor(
  name='gpzs_order',
  full_name='gpzs_order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='gpzs_order.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vol', full_name='gpzs_order.vol', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='gpzs_order.price', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bsflg', full_name='gpzs_order.bsflg', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zsno', full_name='gpzs_order.zsno', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['gpzs_order'] = _GPZS_ORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

gpzs_order = _reflection.GeneratedProtocolMessageType('gpzs_order', (_message.Message,), {
  'DESCRIPTOR' : _GPZS_ORDER,
  '__module__' : 'gpzs_order_pb2'
  # @@protoc_insertion_point(class_scope:gpzs_order)
  })
_sym_db.RegisterMessage(gpzs_order)


# @@protoc_insertion_point(module_scope)
