# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpzs_order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gpzs_order.proto',
  package='',
  serialized_pb=_b('\n\rgpzs_order.proto\"B\n\x07zsorder\x12\x0c\n\x04\x63ode\x18\x01 \x02(\t\x12\x0b\n\x03vol\x18\x02 \x02(\x05\x12\r\n\x05price\x18\x03 \x02(\x02\x12\r\n\x05\x62sflg\x18\x04 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ZSORDER = _descriptor.Descriptor(
  name='zsorder',
  full_name='zsorder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='zsorder.code', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vol', full_name='zsorder.vol', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price', full_name='zsorder.price', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bsflg', full_name='zsorder.bsflg', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['zsorder'] = _ZSORDER

zsorder = _reflection.GeneratedProtocolMessageType('zsorder', (_message.Message,), dict(
  DESCRIPTOR = _ZSORDER,
  __module__ = 'zsorder_pb2'
  # @@protoc_insertion_point(class_scope:zsorder)
  ))
_sym_db.RegisterMessage(zsorder)


# @@protoc_insertion_point(module_scope)
